apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsschool-app
  annotations:
    kubernetes.io/change-cause: "First release kuard-amd64:1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opsschool-app
  template:
    metadata:
      labels:
        app: opsschool-app
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP