
apiVersion: v1
kind: Service
metadata:
  name: kalandula
spec:
  selector:
    app: kalandula
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30037
      protocol: TCP