apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula-app
  annotations:
    kubernetes.io/change-cause: "First release of kandula"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kandula-app
  template:
    metadata:
      labels:
        app: kandula-app
    spec:
      containers:
        - name: kandula-app
          image: erandocker/ops-school-kandula:latest
          ports:
              name: http
              protocol: TCP